<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-26T21:36:11 IST" name="Suite" finished-at="2023-08-26T21:36:40 IST" duration-ms="29705">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidations.LoginErrorValidation()[pri:0, instance:RaahulShettyAcademyy.tests.ErrorValidations@5023bb8b]" name="LoginErrorValidation" class="RaahulShettyAcademyy.tests.ErrorValidations"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:RaahulShettyAcademyy.tests.SubmitOrderTest@6ee6f53]" name="submitOrder" class="RaahulShettyAcademyy.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-08-26T21:36:11 IST" name="Test1" finished-at="2023-08-26T21:36:37 IST" duration-ms="26770">
      <class name="RaahulShettyAcademyy.tests.ErrorValidations">
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:RaahulShettyAcademyy.tests.ErrorValidations@5023bb8b]" started-at="2023-08-26T21:36:11 IST" name="LoginErrorValidation" finished-at="2023-08-26T21:36:23 IST" duration-ms="12776" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at RaahulShettyAcademyy.tests.ErrorValidations.LoginErrorValidation(ErrorValidations.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:RaahulShettyAcademyy.tests.ErrorValidations@5023bb8b]" started-at="2023-08-26T21:36:23 IST" name="tearDown" finished-at="2023-08-26T21:36:23 IST" duration-ms="120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:RaahulShettyAcademyy.tests.ErrorValidations@5023bb8b]" started-at="2023-08-26T21:36:23 IST" name="LoginErrorValidation" finished-at="2023-08-26T21:36:31 IST" duration-ms="7455" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at RaahulShettyAcademyy.tests.ErrorValidations.LoginErrorValidation(ErrorValidations.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:RaahulShettyAcademyy.tests.ErrorValidations@5023bb8b]" started-at="2023-08-26T21:36:31 IST" name="tearDown" finished-at="2023-08-26T21:36:32 IST" duration-ms="155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:RaahulShettyAcademyy.tests.ErrorValidations@5023bb8b]" started-at="2023-08-26T21:36:32 IST" name="ProductErrorValidation" finished-at="2023-08-26T21:36:37 IST" duration-ms="5574" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:RaahulShettyAcademyy.tests.ErrorValidations@5023bb8b]" started-at="2023-08-26T21:36:37 IST" name="tearDown" finished-at="2023-08-26T21:36:37 IST" duration-ms="111" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- RaahulShettyAcademyy.tests.ErrorValidations -->
    </test> <!-- Test1 -->
    <test started-at="2023-08-26T21:36:11 IST" name="Test" finished-at="2023-08-26T21:36:40 IST" duration-ms="29705">
      <class name="RaahulShettyAcademyy.tests.SubmitOrderTest">
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:RaahulShettyAcademyy.tests.SubmitOrderTest@6ee6f53]" started-at="2023-08-26T21:36:11 IST" name="submitOrder" data-provider="getData" finished-at="2023-08-26T21:36:27 IST" duration-ms="15807" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=1234Tarak@, product=ZARA COAT 3, email=1234taraka@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:RaahulShettyAcademyy.tests.SubmitOrderTest@6ee6f53]" started-at="2023-08-26T21:36:27 IST" name="tearDown" finished-at="2023-08-26T21:36:27 IST" duration-ms="72" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:RaahulShettyAcademyy.tests.SubmitOrderTest@6ee6f53]" started-at="2023-08-26T21:36:27 IST" name="submitOrder" data-provider="getData" finished-at="2023-08-26T21:36:35 IST" duration-ms="7836" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=1234Tarak@, product=ZARA COAT 3, email=1234taraka@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:RaahulShettyAcademyy.tests.SubmitOrderTest@6ee6f53]" started-at="2023-08-26T21:36:35 IST" name="tearDown" finished-at="2023-08-26T21:36:35 IST" duration-ms="271" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:RaahulShettyAcademyy.tests.SubmitOrderTest@6ee6f53]" started-at="2023-08-26T21:36:35 IST" name="OrderHistoryTest" finished-at="2023-08-26T21:36:40 IST" depends-on-methods="RaahulShettyAcademyy.tests.SubmitOrderTest.submitOrder" duration-ms="5258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:RaahulShettyAcademyy.tests.SubmitOrderTest@6ee6f53]" started-at="2023-08-26T21:36:40 IST" name="tearDown" finished-at="2023-08-26T21:36:40 IST" duration-ms="155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- RaahulShettyAcademyy.tests.SubmitOrderTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
